name: 'Create archive'
description: 'Create archive for ConcurrentWitness2Test'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt install python3
    - name: Create archive
      shell: bash
      run: ./package.sh
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ConcurrentWitness2Test
        path: ConcurrentWitness2Test.zip
