name: 'Create archive'
description: 'Create archive for ConcurrentWitness2Test'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt install python3
    - name: Create venv
      shell: bash
      run: |
        python3 -m venv --copies venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Create zip
      shell: bash
      run: |
        mkdir ConcurrentWitness2Test
        cp venv *.py *.md LICENSE requirements.txt svcomp.c start.sh ConcurrentWitness2Test/ -r
        zip ConcurrentWitness2Test.zip ConcurrentWitness2Test -r
    - name: Upload results
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: ConcurrentWitness2Test
        path: ConcurrentWitness2Test.zip
