name: Black Check

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

jobs:
  black:
    name: Check Python Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check code formatting with Black
        run: black --check .
